### ISSUE TITLE
We can’t seem to deploy this as-is

### ISSUE THREAD

**Issue by aarongustafson** [gericci/working-hours#1]
From my colleague:

There are a couple problems with his code:

* It should be app.js (although index.js might work too, never tried it)
* It has the listening port hardcoded to 9999 in line #166. It should be something like:

```
var port = process.env.PORT || 9999;
app.listen(port);
console.log(`${port} is the magic port`);
```

If you can adjust the port piece (and/or the index file name) we can try deploying again.

**Comment by cluster** [comment]
It should be fine now. Please let me know if there is something else I can do. :)
